package Hibernate.Entity;
// Generated Dec 9, 2017 11:47:12 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DetalleVentaId generated by hbm2java
 */
@Embeddable
public class DetalleVentaId  implements java.io.Serializable {


     private int idCliente;
     private int idFactura;
     private String idItem;

    public DetalleVentaId() {
    }

    public DetalleVentaId(int idCliente, int idFactura, String idItem) {
       this.idCliente = idCliente;
       this.idFactura = idFactura;
       this.idItem = idItem;
    }
   


    @Column(name="id_cliente", nullable=false)
    public int getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(int idCliente) {
        this.idCliente = idCliente;
    }


    @Column(name="id_factura", nullable=false)
    public int getIdFactura() {
        return this.idFactura;
    }
    
    public void setIdFactura(int idFactura) {
        this.idFactura = idFactura;
    }


    @Column(name="id_item", nullable=false, length=5)
    public String getIdItem() {
        return this.idItem;
    }
    
    public void setIdItem(String idItem) {
        this.idItem = idItem;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DetalleVentaId) ) return false;
		 DetalleVentaId castOther = ( DetalleVentaId ) other; 
         
		 return (this.getIdCliente()==castOther.getIdCliente())
 && (this.getIdFactura()==castOther.getIdFactura())
 && ( (this.getIdItem()==castOther.getIdItem()) || ( this.getIdItem()!=null && castOther.getIdItem()!=null && this.getIdItem().equals(castOther.getIdItem()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdCliente();
         result = 37 * result + this.getIdFactura();
         result = 37 * result + ( getIdItem() == null ? 0 : this.getIdItem().hashCode() );
         return result;
   }   


}


