package hibernate.entities;
// Generated Dec 10, 2017 9:11:34 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DetalleVenta generated by hbm2java
 */
@Entity
@Table(name="detalle_venta"
    ,catalog="customers"
)
public class DetalleVenta  implements java.io.Serializable {


     private DetalleVentaId id;
     private int cantidad;
     private Date fecha;

    public DetalleVenta() {
    }

	
    public DetalleVenta(DetalleVentaId id, int cantidad) {
        this.id = id;
        this.cantidad = cantidad;
    }
    public DetalleVenta(DetalleVentaId id, int cantidad, Date fecha) {
       this.id = id;
       this.cantidad = cantidad;
       this.fecha = fecha;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idCliente", column=@Column(name="id_cliente", nullable=false) ), 
        @AttributeOverride(name="idFactura", column=@Column(name="id_factura", nullable=false) ), 
        @AttributeOverride(name="idItem", column=@Column(name="id_item", nullable=false, length=5) ) } )
    public DetalleVentaId getId() {
        return this.id;
    }
    
    public void setId(DetalleVentaId id) {
        this.id = id;
    }

    
    @Column(name="cantidad", nullable=false)
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


