package hibernate.entities;
// Generated Dec 10, 2017 9:11:34 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Item generated by hbm2java
 */
@Entity
@Table(name="item"
    ,catalog="customers"
)
public class Item  implements java.io.Serializable {


     private String idItem;
     private String nombre;
     private String descripcion;
     private Integer precio;

    public Item() {
    }

	
    public Item(String idItem) {
        this.idItem = idItem;
    }
    public Item(String idItem, String nombre, String descripcion, Integer precio) {
       this.idItem = idItem;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.precio = precio;
    }
   
     @Id 

    
    @Column(name="id_item", unique=true, nullable=false, length=5)
    public String getIdItem() {
        return this.idItem;
    }
    
    public void setIdItem(String idItem) {
        this.idItem = idItem;
    }

    
    @Column(name="nombre", length=30)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="descripcion", length=100)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="precio")
    public Integer getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Integer precio) {
        this.precio = precio;
    }




}


